<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>AuroraCV.HttpApi</RootNamespace>
        <AssemblyTitle>$(RootNamespace)</AssemblyTitle>
        <Description>Aurora Computer Vision Engine - Http Api Layer.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AuroraCV.Application.Contracts\AuroraCV.Application.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Lion.AbpPro.BasicManagement.HttpApi" />
        <PackageReference Include="Lion.AbpPro.NotificationManagement.HttpApi" />
        <PackageReference Include="Lion.AbpPro.DataDictionaryManagement.HttpApi" />
        <PackageReference Include="Lion.AbpPro.LanguageManagement.HttpApi" />
        <PackageReference Include="Lion.AbpPro.CodeManagement.HttpApi" />
        <PackageReference Include="Lion.AbpPro.TemplateManagement.HttpApi" />
        <PackageReference Include="Lion.AbpPro.DynamicMenuManagement.HttpApi" />
        <PackageReference Include="Lion.AbpPro.ImportExportManagement.HttpApi" />
        <PackageReference Include="Lion.AbpPro.FileManagement.HttpApi" />
        <PackageReference Include="Lion.AbpPro.CacheManagement.HttpApi" />
        <PackageReference Include="Lion.AbpPro.MasterDataManagement.HttpApi" />
    </ItemGroup>
</Project>
