<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\configureawait.props" />
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <RootNamespace />
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Volo.Abp.SettingManagement.Domain.Shared\Volo.Abp.SettingManagement.Domain.Shared.csproj" />
        <ProjectReference Include="..\Volo.Abp.Ddd.Application.Contracts\Volo.Abp.Ddd.Application.Contracts.csproj" />
        <ProjectReference Include="..\Volo.Abp.Authorization.Abstractions\Volo.Abp.Authorization.Abstractions.csproj" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Volo\Abp\SettingManagement\Localization\ApplicationContracts\*.json" />
        <Content Remove="Volo\Abp\SettingManagement\Localization\ApplicationContracts\*.json" />
    </ItemGroup>
</Project>
