<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>AuroraCV.EntityFrameworkCore.Tests</RootNamespace>
        <AssemblyTitle>$(RootNamespace)</AssemblyTitle>
        <Description>Aurora Computer Vision Engine - Entity Framework Core Tests.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Aurora CV Engine\AuroraCV.EntityFrameworkCore\AuroraCV.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\AuroraCV.TestBase\AuroraCV.TestBase.csproj" />
        <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
    </ItemGroup>
</Project>
