<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>AuroraCV.Application.Contracts</RootNamespace>
        <AssemblyTitle>$(RootNamespace)</AssemblyTitle>
        <Description>Aurora Computer Vision Engine - Application Contracts Layer.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AuroraCV.Domain.Shared\AuroraCV.Domain.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Lion.AbpPro.BasicManagement.Application.Contracts" />
        <PackageReference Include="Lion.AbpPro.NotificationManagement.Application.Contracts" />
        <PackageReference Include="Lion.AbpPro.DataDictionaryManagement.Application.Contracts" />
        <PackageReference Include="Lion.AbpPro.LanguageManagement.Application.Contracts" />
        <PackageReference Include="Lion.AbpPro.CodeManagement.Application.Contracts" />
        <PackageReference Include="Lion.AbpPro.TemplateManagement.Application.Contracts" />
        <PackageReference Include="Lion.AbpPro.DynamicMenuManagement.Application.Contracts" />
        <PackageReference Include="Lion.AbpPro.ImportExportManagement.Application.Contracts" />
        <PackageReference Include="Lion.AbpPro.FileManagement.Application.Contracts" />
        <PackageReference Include="Lion.AbpPro.CacheManagement.Application.Contracts" />
        <PackageReference Include="Lion.AbpPro.MasterDataManagement.Application.Contracts" />
    </ItemGroup>
</Project>
