<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <RootNamespace>Lion.AbpPro.FileManagement</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Volo.Abp.EntityFrameworkCore\Volo.Abp.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\Lion.AbpPro.FileManagement.Domain\Lion.AbpPro.FileManagement.Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
            <PrivateAssets>compile; contentFiles; build; buildMultitargeting; buildTransitive; analyzers; native</PrivateAssets>
        </PackageReference>
    </ItemGroup>
</Project>
