<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>AuroraStruct3D.EntityFrameworkCore.Tests</RootNamespace>
        <IsPackable>false</IsPackable>
        <OutputType>Library</OutputType>
        <Description>.aurora-结构体3D EFCore 测试库</Description>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\Sources\AuroraStruct3D\AuroraStruct3D.EntityFrameworkCore\AuroraStruct3D.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\AuroraStruct3D.TestBase\AuroraStruct3D.TestBase.csproj" />
        <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
    </ItemGroup>
</Project>