<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <RootNamespace>Lion.AbpPro.ImportExportManagement</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Volo.Abp.Ddd.Application\Volo.Abp.Ddd.Application.csproj" />
        <ProjectReference Include="..\Lion.AbpPro.FileManagement.Domain\Lion.AbpPro.FileManagement.Domain.csproj" />
        <ProjectReference Include="..\Lion.AbpPro.ImportExportManagement.Application.Contracts\Lion.AbpPro.ImportExportManagement.Application.Contracts.csproj" />
        <ProjectReference Include="..\Lion.AbpPro.ImportExportManagement.Domain\Lion.AbpPro.ImportExportManagement.Domain.csproj" />
    </ItemGroup>
</Project>
