<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <RootNamespace>Lion.AbpPro.MasterDataManagement</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Volo.Abp.EntityFrameworkCore\Volo.Abp.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\Lion.AbpPro.MasterDataManagement.Domain\Lion.AbpPro.MasterDataManagement.Domain.csproj" />
    </ItemGroup>
</Project>
