<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AuroraStruct3D.Application.Contracts\AuroraStruct3D.Application.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.BasicManagement.HttpApi\Lion.AbpPro.BasicManagement.HttpApi.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.NotificationManagement.HttpApi\Lion.AbpPro.NotificationManagement.HttpApi.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.DataDictionaryManagement.HttpApi\Lion.AbpPro.DataDictionaryManagement.HttpApi.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.LanguageManagement.HttpApi\Lion.AbpPro.LanguageManagement.HttpApi.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.CodeManagement.HttpApi\Lion.AbpPro.CodeManagement.HttpApi.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.TemplateManagement.HttpApi\Lion.AbpPro.TemplateManagement.HttpApi.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.DynamicMenuManagement.HttpApi\Lion.AbpPro.DynamicMenuManagement.HttpApi.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.ImportExportManagement.HttpApi\Lion.AbpPro.ImportExportManagement.HttpApi.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.FileManagement.HttpApi\Lion.AbpPro.FileManagement.HttpApi.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.CacheManagement.HttpApi\Lion.AbpPro.CacheManagement.HttpApi.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.MasterDataManagement.HttpApi\Lion.AbpPro.MasterDataManagement.HttpApi.csproj" />
    </ItemGroup>
</Project>
