<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>AuroraStruct3D.Domain</RootNamespace>
        <AssemblyTitle>$(RootNamespace)</AssemblyTitle>
        <Description>Aurora Computer Vision Engine - Domain Layer.</Description>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\AuroraStruct3D.Domain.Shared\AuroraStruct3D.Domain.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Lion.AbpPro.BasicManagement.Domain" />
        <PackageReference Include="Lion.AbpPro.NotificationManagement.Domain" />
        <PackageReference Include="Lion.AbpPro.DataDictionaryManagement.Domain" />
        <PackageReference Include="Lion.AbpPro.LanguageManagement.Domain" />
        <PackageReference Include="Lion.AbpPro.CodeManagement.Domain" />
        <PackageReference Include="Lion.AbpPro.TemplateManagement.Domain" />
        <PackageReference Include="Lion.AbpPro.DynamicMenuManagement.Domain" />
        <PackageReference Include="Lion.AbpPro.ImportExportManagement.Domain" />
        <PackageReference Include="Lion.AbpPro.FileManagement.Domain" />
        <PackageReference Include="Lion.AbpPro.CacheManagement.Domain" />
        <PackageReference Include="Lion.AbpPro.MasterDataManagement.Domain" />
    </ItemGroup>
</Project>
