<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <RootNamespace>Lion.AbpPro.MasterDataManagement</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Volo.Abp.Ddd.Application.Contracts\Volo.Abp.Ddd.Application.Contracts.csproj" />
        <ProjectReference Include="..\Volo.Abp.Authorization\Volo.Abp.Authorization.csproj" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Lion.AbpPro.MasterDataManagement.Domain.Shared\Lion.AbpPro.MasterDataManagement.Domain.Shared.csproj" />
    </ItemGroup>
</Project>
