<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>FringeTool</RootNamespace>
    <AssemblyName>FringeTool</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HidSharp" Version="2.2.0" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

</Project>