<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AuroraStruct3D.Domain.Shared\AuroraStruct3D.Domain.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.BasicManagement.Application.Contracts\Lion.AbpPro.BasicManagement.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.NotificationManagement.Application.Contracts\Lion.AbpPro.NotificationManagement.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.DataDictionaryManagement.Application.Contracts\Lion.AbpPro.DataDictionaryManagement.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.LanguageManagement.Application.Contracts\Lion.AbpPro.LanguageManagement.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.CodeManagement.Application.Contracts\Lion.AbpPro.CodeManagement.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.TemplateManagement.Application.Contracts\Lion.AbpPro.TemplateManagement.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.DynamicMenuManagement.Application.Contracts\Lion.AbpPro.DynamicMenuManagement.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.ImportExportManagement.Application.Contracts\Lion.AbpPro.ImportExportManagement.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.FileManagement.Application.Contracts\Lion.AbpPro.FileManagement.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.CacheManagement.Application.Contracts\Lion.AbpPro.CacheManagement.Application.Contracts.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.MasterDataManagement.Application.Contracts\Lion.AbpPro.MasterDataManagement.Application.Contracts.csproj" />
    </ItemGroup>
</Project>
