<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AuroraStruct3D.Domain\AuroraStruct3D.Domain.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Volo.Abp.EntityFrameworkCore.PostgreSql\Volo.Abp.EntityFrameworkCore.PostgreSql.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.BasicManagement.EntityFrameworkCore\Lion.AbpPro.BasicManagement.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.NotificationManagement.EntityFrameworkCore\Lion.AbpPro.NotificationManagement.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.DataDictionaryManagement.EntityFrameworkCore\Lion.AbpPro.DataDictionaryManagement.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.LanguageManagement.EntityFrameworkCore\Lion.AbpPro.LanguageManagement.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.CodeManagement.EntityFrameworkCore\Lion.AbpPro.CodeManagement.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.TemplateManagement.EntityFrameworkCore\Lion.AbpPro.TemplateManagement.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.DynamicMenuManagement.EntityFrameworkCore\Lion.AbpPro.DynamicMenuManagement.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.ImportExportManagement.EntityFrameworkCore\Lion.AbpPro.ImportExportManagement.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.FileManagement.EntityFrameworkCore\Lion.AbpPro.FileManagement.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\AuroraAbpPro\Lion.AbpPro.MasterDataManagement.EntityFrameworkCore\Lion.AbpPro.MasterDataManagement.EntityFrameworkCore.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
            <PrivateAssets>compile; contentFiles; build; buildMultitargeting; buildTransitive; analyzers; native</PrivateAssets>
        </PackageReference>
    </ItemGroup>
</Project>
