"""读取 leisai-params.json 生成 C# 参数目录与 TS 元数据类型常量。"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON = ROOT / "Tools" / "leisai-params.json"
CS_OUT = (
    ROOT
    / "Sources"
    / "AuroraStruct3D"
    / "AuroraStruct3D.Application"
    / "Leisai"
    / "Catalog"
    / "LeisaiParameterCatalog.cs"
)

data = json.loads(JSON.read_text(encoding="utf-8"))

GROUP_NAMES = {
    0: "基础参数",
    1: "增益与滤波 (Pr1)",
    2: "高级控制 (Pr2)",
    3: "保留 (Pr3)",
    4: "IO 与制动 (Pr4)",
    5: "电流/通讯 (Pr5)",
    6: "JOG / 试运行 (Pr6)",
    7: "电机/电流环 (Pr7)",
    8: "PR 控制与回零 (Pr8)",
    9: "PR 路径配置 (Pr9)",
}


def clean(s: str | None) -> str:
    if not s:
        return ""
    s = re.sub(r"\s+", " ", s).strip()
    # 紧凑数字 + 单位/小数
    s = re.sub(r"(?<=\d)\s+\.\s+(?=\d)", ".", s)  # "0 . 1A" → "0.1A"
    s = s.replace(" ：", "：").replace(": ", "：")
    return s


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def is_signed(r) -> bool:
    return r["rangeMin"] is not None and r["rangeMin"] < 0


def kind(r) -> str:
    rmin = r["rangeMin"]
    rmax = r["rangeMax"]
    if rmin is None or rmax is None:
        return "Uint16"
    if rmin < -32768 or rmax > 65535:
        return "Int32Pair"  # 32位高低分割（信息提示，实际仍按 uint16 编辑）
    return "Int16" if rmin < 0 else "Uint16"


def cs_int(v) -> str:
    return "null" if v is None else str(v)


lines: list[str] = []
lines.append("// <auto-generated>")
lines.append("// 由 Tools/Generate-LeisaiCatalog.py 从 Tools/leisai-params.json 生成。")
lines.append("// 请勿手动修改，重新生成请执行该 Python 脚本。")
lines.append("// </auto-generated>")
lines.append("using System.Collections.Generic;")
lines.append("using AuroraStruct3D.Leisai.Dtos;")
lines.append("")
lines.append("namespace AuroraStruct3D.Leisai.Catalog;")
lines.append("")
lines.append("/// <summary>")
lines.append("/// 雷赛 iCL-RS(V2.0) 全部 RW 参数静态目录（来自《电机命令2.htm》）。")
lines.append(f"/// 共 {len(data)} 个参数。")
lines.append("/// </summary>")
lines.append("public static class LeisaiParameterCatalog")
lines.append("{")
lines.append("    /// <summary>分组名称表。</summary>")
lines.append(
    "    public static readonly IReadOnlyDictionary<int, string> GroupNames = new Dictionary<int, string>"
)
lines.append("    {")
for g, n in GROUP_NAMES.items():
    lines.append(f'        [{g}] = "{esc(n)}",')
lines.append("    };")
lines.append("")
lines.append("    /// <summary>全部参数定义（按地址升序）。</summary>")
lines.append(
    "    public static readonly IReadOnlyList<LeisaiParameterMetadataDto> All = new LeisaiParameterMetadataDto[]"
)
lines.append("    {")
for r in data:
    name = esc(clean(r["name"]))
    defn = esc(clean(r["definition"]))
    unit = clean(r["unit"])
    if unit in ("--", "—", "-"):
        unit = ""
    unit_esc = esc(unit)
    k = kind(r)
    lines.append("        new()")
    lines.append("        {")
    lines.append(f"            Pr = \"{r['pr']}\",")
    lines.append(f"            Group = {r['group']},")
    lines.append(f"            AddressLow = 0x{r['addressLow']:04X},")
    lines.append(f'            Name = "{name}",')
    lines.append(f'            Description = "{defn}",')
    lines.append(f'            Unit = "{unit_esc}",')
    lines.append(f"            RangeMin = {cs_int(r['rangeMin'])},")
    lines.append(f"            RangeMax = {cs_int(r['rangeMax'])},")
    lines.append(f"            DefaultValue = {cs_int(r['defaultValue'])},")
    lines.append(f"            DataKind = LeisaiParamDataKind.{k},")
    lines.append("        },")
lines.append("    };")
lines.append("}")
lines.append("")

CS_OUT.parent.mkdir(parents=True, exist_ok=True)
CS_OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"生成 {CS_OUT}（{len(data)} 项）")
