<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\configureawait.props" />
    <Import Project="..\..\..\common.props" />
    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <AssemblyName>Volo.Abp.HangFire</AssemblyName>
        <PackageId>Volo.Abp.HangFire</PackageId>
        <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
        <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
        <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
        <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
        <RootNamespace />
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Hangfire.AspNetCore\Hangfire.AspNetCore.csproj" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.2" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Volo.Abp.Authorization.Abstractions\Volo.Abp.Authorization.Abstractions.csproj" />
        <ProjectReference Include="..\Volo.Abp.Core\Volo.Abp.Core.csproj" />
    </ItemGroup>
</Project>
